args:
  bl: 0.14962844133819508
  camera:
    cx: 387.4557098388672
    cy: 224.2397003173828
    fx: 226.0792895029649
    fy: 226.0792895029649
  data_config_file: /app/FDCPost/config/test_config.yaml
  format: png
  result_root: /app/FDCPost/data/2ed0/session_20251106_061007_302604/processed/down
name: down
type: GeneralStereo
